Repository knative/actions, pull requests merged in 2022-10, with the labels that each got.

#70 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#72 :gift: Use Knative ls-tags tool
  .github/workflows/go-build.yaml
  .github/workflows/reusable-go-build.yaml
  go/downstream-test/action.yaml
Labels: size/M, kind/enhancement, approved, lgtm

#73 fix double quote error
  .github/workflows/file-syncer.yaml
Labels: size/XS, approved, lgtm

#74 :broom: Simplify the ls-tags execution
  .github/workflows/go-build.yaml
  .github/workflows/reusable-go-build.yaml
  go/downstream-test/action.yaml
Labels: kind/cleanup, size/XS, approved, lgtm

#75 :bug: Do not check vendor dir from sum-modules for Lints
  .github/workflows/style.yaml
Labels: size/S, kind/bug, approved, lgtm

#76 :bug: Don't look at vendor or third_party regardless of location
  .github/workflows/style.yaml
Labels: size/XS, kind/bug, approved, lgtm

#78 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#79 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
