Repository knative/actions, pull requests merged in 2022-04, with the labels that each got.

#17 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, approved, lgtm

#18 update action versions
  .github/workflows/go-build.yaml
  .github/workflows/go-test.yaml
  .github/workflows/lint.yaml
  .github/workflows/releasability.yaml
  .github/workflows/release-notes.yaml
  .github/workflows/security.yaml
  .github/workflows/stale.yaml
  .github/workflows/style.yaml
  .github/workflows/verify-codegen.yaml
Labels: size/M, approved, lgtm

#19 drop version numbers in releasability flow
  .github/workflows/releasability.yaml
Labels: size/S, approved, lgtm

#20 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#21 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#22 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#24 :gift: Configurability of Unicode Control Characters check
  .github/workflows/security.yaml
Labels: size/S, kind/enhancement, approved, lgtm

#26 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
