Repository knative/actions, pull requests merged in 2022-11, with the labels that each got.

#81 Drop unused matrix strategy and some step ids
  .github/workflows/go-build.yaml
  .github/workflows/go-test.yaml
  .github/workflows/reusable-go-build.yaml
  .github/workflows/reusable-go-test.yaml
  .github/workflows/reusable-verify-codegen.yaml
  .github/workflows/style.yaml
  .github/workflows/verify-codegen.yaml
Labels: size/M, approved, lgtm

#82 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#83 Bug in style action
  .github/workflows/style.yaml
Labels: size/XS, approved, lgtm

#84 Fixed Style action
  .github/workflows/style.yaml
Labels: size/XS, approved, lgtm

#85 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#88 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
