Repository knative/actions, pull requests merged in 2022-05, with the labels that each got.

#27 add go/downstream-test
  go/downstream-test/README.md
  go/downstream-test/action.yaml
Labels: size/L, approved, lgtm

#29 Infer the module name from the go.mod file
  go/downstream-test/README.md
  go/downstream-test/action.yaml
Labels: size/M, approved, lgtm

#30 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#31 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#32 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#33 make linting great again
  .github/workflows/lint.yaml
Labels: size/L, approved, lgtm
