Repository knative/actions, pull requests merged in 2023-06, with the labels that each got.

#147 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#149 Shell style action enhancements
  composite/style/shell/action.yml
Labels: size/XS, approved, lgtm

#150 Exclude `third_party` folders from style checks
  .github/workflows/reusable-style.yaml
Labels: size/S, approved, lgtm

#151 Remove reporter config from action-shfmt
  composite/style/shell/action.yml
Labels: size/XS, approved, lgtm

#152 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
