Repository knative/actions, pull requests merged in 2023-07, with the labels that each got.

#155 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#156 Cleanup shell lint action
  composite/style/shell/action.yml
Labels: size/M, approved, lgtm

#157 Use reviewdog shfmt for easier install
  composite/style/shell/action.yml
Labels: size/S, approved, lgtm

#142 removing-redundant-go-fmt
  .github/workflows/reusable-helper-go-style.yaml
Labels: size/S, approved, lgtm

#158 Remove shellfmt
  composite/style/shell/action.yml
Labels: size/XS, approved, lgtm

#159 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#160 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#161 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
