Repository knative/actions, pull requests merged in 2023-11, with the labels that each got.

#175 Support 1.21 for codeQL
  .github/workflows/reusable-security.yaml
Labels: size/XS, approved, lgtm

#176 Make SECURITY.md consistent
  SECURITY.md
Labels: do-not-merge/hold, size/XS, approved, lgtm

#178 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
