Repository knative/actions, pull requests merged in 2023-08, with the labels that each got.

#162 Rename knative-sandbox to knative-extensions
  go/downstream-test/README.md
Labels: size/XS, approved, lgtm

#163 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#164 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#165 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
