Repository knative/actions, pull requests merged in 2023-05, with the labels that each got.

#138 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#140 Exclude SC1091 checks
  .github/workflows/reusable-style.yaml
  composite/style/shell/action.yml
Labels: size/S, approved, lgtm

#141 Action doesn't use short major version
  composite/style/shell/action.yml
Labels: size/XS, approved, lgtm

#143 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
