Repository knative/actions, pull requests merged in 2024-09, with the labels that each got.

#223 :gift_heart: Run Go tests for each module
  .github/workflows/reusable-go-build.yaml
  .github/workflows/reusable-go-test.yaml
Labels: size/M, kind/enhancement, approved, lgtm

#224 :lady_beetle: Prevent slash from appearing in coverage random ID
  .github/workflows/reusable-go-test.yaml
Labels: size/XS, kind/bug, approved, lgtm

#225 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
